package com.xworkz.abstraction.rbiapp;

import com.xworkz.abstraction.rbiapp.bank.*;
import com.xworkz.abstraction.rbiapp.rbi.Rbi;

public class RbiBankRunner {

    public static void main(String[] args) {

        Rbi rbi = new CanaraBank();

        rbi.kyc();
        rbi.openAccount();
        rbi.closeAccount();
        rbi.deposit();
        rbi.withdraw();
        rbi.transferMoney();
        rbi.checkBalance();
        rbi.applyLoan();
        rbi.payLoan();
        rbi.issueDebitCard();
        rbi.issueCreditCard();
        rbi.blockCard();
        rbi.unblockCard();
        rbi.generatePin();
        rbi.changePin();
        rbi.netBanking();
        rbi.mobileBanking();
        rbi.upiService();
        rbi.chequeBook();
        rbi.stopCheque();
        rbi.updateMobileNumber();
        rbi.updateAddress();
        rbi.nomineeService();
        rbi.fixedDeposit();
        rbi.customerSupport();
        System.out.println("___________________________________");

        Rbi rbi1 = new StateBankOfIndia();

        rbi1.kyc();
        rbi1.openAccount();
        rbi1.closeAccount();
        rbi1.deposit();
        rbi1.withdraw();
        rbi1.transferMoney();
        rbi1.checkBalance();
        rbi1.applyLoan();
        rbi1.payLoan();
        rbi1.issueDebitCard();
        rbi1.issueCreditCard();
        rbi1.blockCard();
        rbi1.unblockCard();
        rbi1.generatePin();
        rbi1.changePin();
        rbi1.netBanking();
        rbi1.mobileBanking();
        rbi1.upiService();
        rbi1.chequeBook();
        rbi1.stopCheque();
        rbi1.updateMobileNumber();
        rbi1.updateAddress();
        rbi1.nomineeService();
        rbi1.fixedDeposit();
        rbi1.customerSupport();
        System.out.println("___________________________________");

        Rbi rbi2 = new HdfcBank();

        rbi2.kyc();
        rbi2.openAccount();
        rbi2.closeAccount();
        rbi2.deposit();
        rbi2.withdraw();
        rbi2.transferMoney();
        rbi2.checkBalance();
        rbi2.applyLoan();
        rbi2.payLoan();
        rbi2.issueDebitCard();
        rbi2.issueCreditCard();
        rbi2.blockCard();
        rbi2.unblockCard();
        rbi2.generatePin();
        rbi2.changePin();
        rbi2.netBanking();
        rbi2.mobileBanking();
        rbi2.upiService();
        rbi2.chequeBook();
        rbi2.stopCheque();
        rbi2.updateMobileNumber();
        rbi2.updateAddress();
        rbi2.nomineeService();
        rbi2.fixedDeposit();
        rbi2.customerSupport();
        System.out.println("___________________________________");

        Rbi rbi3 = new IciciBank();

        rbi3.kyc();
        rbi3.openAccount();
        rbi3.closeAccount();
        rbi3.deposit();
        rbi3.withdraw();
        rbi3.transferMoney();
        rbi3.checkBalance();
        rbi3.applyLoan();
        rbi3.payLoan();
        rbi3.issueDebitCard();
        rbi3.issueCreditCard();
        rbi3.blockCard();
        rbi3.unblockCard();
        rbi3.generatePin();
        rbi3.changePin();
        rbi3.netBanking();
        rbi3.mobileBanking();
        rbi3.upiService();
        rbi3.chequeBook();
        rbi3.stopCheque();
        rbi3.updateMobileNumber();
        rbi3.updateAddress();
        rbi3.nomineeService();
        rbi3.fixedDeposit();
        rbi3.customerSupport();
        System.out.println("___________________________________");

        Rbi rbi4 = new AxisBank();

        rbi4.kyc();
        rbi4.openAccount();
        rbi4.closeAccount();
        rbi4.deposit();
        rbi4.withdraw();
        rbi4.transferMoney();
        rbi4.checkBalance();
        rbi4.applyLoan();
        rbi4.payLoan();
        rbi4.issueDebitCard();
        rbi4.issueCreditCard();
        rbi4.blockCard();
        rbi4.unblockCard();
        rbi4.generatePin();
        rbi4.changePin();
        rbi4.netBanking();
        rbi4.mobileBanking();
        rbi4.upiService();
        rbi4.chequeBook();
        rbi4.stopCheque();
        rbi4.updateMobileNumber();
        rbi4.updateAddress();
        rbi4.nomineeService();
        rbi4.fixedDeposit();
        rbi4.customerSupport();
        System.out.println("___________________________________");

        Rbi rbi5 = new BankOfBaroda();

        rbi5.kyc();
        rbi5.openAccount();
        rbi5.closeAccount();
        rbi5.deposit();
        rbi5.withdraw();
        rbi5.transferMoney();
        rbi5.checkBalance();
        rbi5.applyLoan();
        rbi5.payLoan();
        rbi5.issueDebitCard();
        rbi5.issueCreditCard();
        rbi5.blockCard();
        rbi5.unblockCard();
        rbi5.generatePin();
        rbi5.changePin();
        rbi5.netBanking();
        rbi5.mobileBanking();
        rbi5.upiService();
        rbi5.chequeBook();
        rbi5.stopCheque();
        rbi5.updateMobileNumber();
        rbi5.updateAddress();
        rbi5.nomineeService();
        rbi5.fixedDeposit();
        rbi5.customerSupport();
        System.out.println("___________________________________");

        Rbi rbi6 = new PunjabNationalBank();

        rbi6.kyc();
        rbi6.openAccount();
        rbi6.closeAccount();
        rbi6.deposit();
        rbi6.withdraw();
        rbi6.transferMoney();
        rbi6.checkBalance();
        rbi6.applyLoan();
        rbi6.payLoan();
        rbi6.issueDebitCard();
        rbi6.issueCreditCard();
        rbi6.blockCard();
        rbi6.unblockCard();
        rbi6.generatePin();
        rbi6.changePin();
        rbi6.netBanking();
        rbi6.mobileBanking();
        rbi6.upiService();
        rbi6.chequeBook();
        rbi6.stopCheque();
        rbi6.updateMobileNumber();
        rbi6.updateAddress();
        rbi6.nomineeService();
        rbi6.fixedDeposit();
        rbi6.customerSupport();
        System.out.println("___________________________________");

        Rbi rbi7 = new UnionBankOfIndia();

        rbi7.kyc();
        rbi7.openAccount();
        rbi7.closeAccount();
        rbi7.deposit();
        rbi7.withdraw();
        rbi7.transferMoney();
        rbi7.checkBalance();
        rbi7.applyLoan();
        rbi7.payLoan();
        rbi7.issueDebitCard();
        rbi7.issueCreditCard();
        rbi7.blockCard();
        rbi7.unblockCard();
        rbi7.generatePin();
        rbi7.changePin();
        rbi7.netBanking();
        rbi7.mobileBanking();
        rbi7.upiService();
        rbi7.chequeBook();
        rbi7.stopCheque();
        rbi7.updateMobileNumber();
        rbi7.updateAddress();
        rbi7.nomineeService();
        rbi7.fixedDeposit();
        rbi7.customerSupport();
        System.out.println("___________________________________");

        Rbi rbi8 = new BankOfIndia();

        rbi8.kyc();
        rbi8.openAccount();
        rbi8.closeAccount();
        rbi8.deposit();
        rbi8.withdraw();
        rbi8.transferMoney();
        rbi8.checkBalance();
        rbi8.applyLoan();
        rbi8.payLoan();
        rbi8.issueDebitCard();
        rbi8.issueCreditCard();
        rbi8.blockCard();
        rbi8.unblockCard();
        rbi8.generatePin();
        rbi8.changePin();
        rbi8.netBanking();
        rbi8.mobileBanking();
        rbi8.upiService();
        rbi8.chequeBook();
        rbi8.stopCheque();
        rbi8.updateMobileNumber();
        rbi8.updateAddress();
        rbi8.nomineeService();
        rbi8.fixedDeposit();
        rbi8.customerSupport();
        System.out.println("___________________________________");

        Rbi rbi9 = new IndianBank();

        rbi9.kyc();
        rbi9.openAccount();
        rbi9.closeAccount();
        rbi9.deposit();
        rbi9.withdraw();
        rbi9.transferMoney();
        rbi9.checkBalance();
        rbi9.applyLoan();
        rbi9.payLoan();
        rbi9.issueDebitCard();
        rbi9.issueCreditCard();
        rbi9.blockCard();
        rbi9.unblockCard();
        rbi9.generatePin();
        rbi9.changePin();
        rbi9.netBanking();
        rbi9.mobileBanking();
        rbi9.upiService();
        rbi9.chequeBook();
        rbi9.stopCheque();
        rbi9.updateMobileNumber();
        rbi9.updateAddress();
        rbi9.nomineeService();
        rbi9.fixedDeposit();
        rbi9.customerSupport();
    }
}
